# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
# This is required to provide enough memory for the Minecraft decompilation process.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17
minecraft_version=1.21.1
minecraft_version_range=[1.21,1.21.1)
neo_version=21.1.187
neo_version_range=[21.1.93,)
loader_version_range=[4,)

## Mod Properties

mod_id=ancientreforging
mod_name=Ancient Reforging
mod_license=MIT
mod_version=1.8
mod_group_id=ianm1647.ancientreforging
mod_authors=ianm1647
mod_description=Adds a third reforging table for higher tier reforging!

## Mod Dependencies
jei_version=19.21.2.313
architectury_version=13.0.8
apotheosis_version=8.4.0
placebo_version=9.9.1
attributeslib_version=2.9.0
spawners_version=1.3.2
enchanting_version=1.5.0
gateways_version=5.1.0
patchouli_version=1.21-88-NEOFORGE
curios_version=9.5.1+1.21.1
jade_version=6738687